mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\volkswagen
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\audi
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\jeep
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\skoda
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\bmw
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\peugeot
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\mazda
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\nissan
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\ford
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\renault
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\mercedes_benz
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\seat
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\honda
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\fiat
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\opel
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\mini
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\smart
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\hyundai
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\sonstige_autos
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\alfa_romeo
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\subaru
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\volvo
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\mitsubishi
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\kia
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\suzuki
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\lancia
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\citroen
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\toyota
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\chevrolet
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\dacia
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\daihatsu
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\trabant
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\saab
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\chrysler
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\jaguar
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\daewoo
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\porsche
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\rover
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\land_rover
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis\lada
mkdir c:\Users\LEGION\pad_project_s31061\cleaned_data\data_for_analysis
