mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/volkswagen
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/audi
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/jeep
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/skoda
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/bmw
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/peugeot
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/mazda
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/nissan
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/ford
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/renault
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/mercedes_benz
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/seat
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/honda
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/fiat
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/opel
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/mini
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/smart
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/hyundai
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/sonstige_autos
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/alfa_romeo
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/subaru
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/volvo
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/mitsubishi
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/kia
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/suzuki
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/lancia
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/citroen
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/toyota
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/chevrolet
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/dacia
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/daihatsu
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/trabant
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/saab
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/chrysler
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/jaguar
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/daewoo
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/porsche
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/rover
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/land_rover
mkdirc:\Users\LEGION\pad_project_s31061\/cleaned_data/lada
mkdir -p c:\Users\LEGION\pad_project_s31061\/cleaned_data/